// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFehZuY0TFGPYvlOw8aoVniLp9WPrfZuY',
    appId: '1:42899798269:web:4f803b9b47b62b46b8a694',
    messagingSenderId: '42899798269',
    projectId: 'sinflix-a0921',
    authDomain: 'sinflix-a0921.firebaseapp.com',
    storageBucket: 'sinflix-a0921.firebasestorage.app',
    measurementId: 'G-6REGTHV580',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUKKekxz4Zj7AvMMVdEar6rBg1Cd9Q5kA',
    appId: '1:42899798269:android:3568cc704b3b7374b8a694',
    messagingSenderId: '42899798269',
    projectId: 'sinflix-a0921',
    storageBucket: 'sinflix-a0921.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALd5VHWim8JkQkD5wU0SMjgl1Z_qNwaNw',
    appId: '1:42899798269:ios:7f3d5f8959baf687b8a694',
    messagingSenderId: '42899798269',
    projectId: 'sinflix-a0921',
    storageBucket: 'sinflix-a0921.firebasestorage.app',
    iosBundleId: 'com.example.sinflix',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALd5VHWim8JkQkD5wU0SMjgl1Z_qNwaNw',
    appId: '1:42899798269:ios:7f3d5f8959baf687b8a694',
    messagingSenderId: '42899798269',
    projectId: 'sinflix-a0921',
    storageBucket: 'sinflix-a0921.firebasestorage.app',
    iosBundleId: 'com.example.sinflix',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFehZuY0TFGPYvlOw8aoVniLp9WPrfZuY',
    appId: '1:42899798269:web:44c9a75e93af9087b8a694',
    messagingSenderId: '42899798269',
    projectId: 'sinflix-a0921',
    authDomain: 'sinflix-a0921.firebaseapp.com',
    storageBucket: 'sinflix-a0921.firebasestorage.app',
    measurementId: 'G-59GYR6P2KC',
  );
}
